{
 "title": "Flow Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Switches with IP Fragment Drops",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "IngressDrops_IPFragmentDrops > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vnic Policy Drops",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "VnicDrops_PolicyDrops", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Vnic Vmotion Transient Drops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "VnicDrops_VmotionTransientDrops",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vnic Session State Drops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "VnicDrops_UnexpectedSessionStateDrops",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Sessions Over IPv4",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(FlowStatsSummary_UDPSessionsOverIPv4) - sum(FlowStatsSummary_DeletedUDPSessionsOverIPv4)",
     "legendFormat": "UDP"
    },
    {
     "expr": "sum(FlowStatsSummary_TCPSessionsOverIPv4) - sum(FlowStatsSummary_DeletedTCPSessionsOverIPv4)",
     "legendFormat": "TCP"
    },
    {
     "expr": "sum(FlowStatsSummary_ICMPSessionsOverIPv4) - sum(FlowStatsSummary_DeletedICMPSessionsOverIPv4)",
     "legendFormat": "ICMP"
    },
    {
     "expr": "sum(FlowStatsSummary_OtherSessionsOverIPv4) - sum(FlowStatsSummary_DeletedOtherSessionsOverIPv4)",
     "legendFormat": "Other"
    },
    {
     "expr": "sum(FlowStatsSummary_L2Sessions) - sum(FlowStatsSummary_DeletedL2Sessions)",
     "legendFormat": "L2"
    }
   ]
  },
  {
   "title": "UDP Sessions over IPv4",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(FlowStatsSummary_UDPSessionsOverIPv4 - FlowStatsSummary_DeletedUDPSessionsOverIPv4) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP Sessions Over IPv4",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(FlowStatsSummary_TCPSessionsOverIPv4 - FlowStatsSummary_DeletedTCPSessionsOverIPv4) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ICMP Sessions Over IPv4",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(FlowStatsSummary_ICMPSessionsOverIPv4 - FlowStatsSummary_DeletedICMPSessionsOverIPv4) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other Sessions Over IPv4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 12 },
   "targets": [
    {
     "expr": "(FlowStatsSummary_OtherSessionsOverIPv4 - FlowStatsSummary_DeletedOtherSessionsOverIPv4)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L2 Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 12 },
   "targets": [
    {
     "expr": "(FlowStatsSummary_L2Sessions - FlowStatsSummary_DeletedL2Sessions)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets That Hit Policy Rules",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "RuleMetrics_Hits > 0 ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ConnTrack Disabled Sessions Over IPv4",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " FlowStatsSummary_ConnTrackDisabledSessionsOverIPv4 - FlowStatsSummary_DeletedConnTrackDisabledSessionsOverIPv4",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SessionCreateErrors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "FlowStatsSummary_SessionCreateErrors",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rx Unicast Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "LifMetrics_RxUnicastBytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tx Unicast Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "LifMetrics_TxUnicastBytes", "legendFormat": "__auto" }
   ]
  }
 ]
}