{
 "title": "Per Switch Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Switch",
    "query": {
     "query": "label_values(DSC_dsc_version,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Switch Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "DSC_node{node=\"$Switch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ELBA Enabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DSC_ELBA_enabled", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Switch Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DSC_health_status{node=\"$Switch\"}"
    }
   ]
  },
  {
   "title": "Total DSS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Cluster_AdmittedNICs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# VRFs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DSC_Number_of_vrfs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# VLANs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DSC_Number_of_networks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ASIC Die Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AsicTemperatureMetrics_DieTemperature{node=\"$Switch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ASIC Local Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AsicTemperatureMetrics_LocalTemperature{node=\"$Switch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(MemoryMetrics_Totalmemory{node=\"$Switch\"} - MemoryMetrics_Freememory{node=\"$Switch\"}) / MemoryMetrics_Totalmemory{node=\"$Switch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AsicCpuMetrics_Usage{node=\"$Switch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active IPv4 TCP Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "FlowStatsSummary_TCPSessionsOverIPv4{node=\"$Switch\"} - FlowStatsSummary_DeletedTCPSessionsOverIPv4{node=\"$Switch\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active IPv4 UDP Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "FlowStatsSummary_UDPSessionsOverIPv4{node=\"$Switch\"} - FlowStatsSummary_DeletedUDPSessionsOverIPv4{node=\"$Switch\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active IPv4 ICMP Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "FlowStatsSummary_ICMPSessionsOverIPv4{node=\"$Switch\"} - FlowStatsSummary_DeletedICMPSessionsOverIPv4{node=\"$Switch\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active IPv4 Other Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " FlowStatsSummary_OtherSessionsOverIPv4{node=\"$Switch\"} - FlowStatsSummary_OtherSessionsOverIPv4{node=\"$Switch\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active L2 Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "FlowStatsSummary_L2Sessions{node=\"$Switch\"} - FlowStatsSummary_L2Sessions{node=\"$Switch\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DSM Power In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "PowerMetrics_Pin{node=\"$Switch\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "DSM Power Out1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "PowerMetrics_Pout1{node=\"$Switch\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "DSM Power Out2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "PowerMetrics_Pout2{node=\"$Switch\"}",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}