{
 "title": "PSM Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "PSM_Node",
    "query": {
     "query": "label_values(Node_CPUUsedPercent,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "Cluster_Node_IP", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Used Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Node_MemUsedPercent{node=~\"$PSM_Node\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Node_CPUUsedPercent{node=~\"$PSM_Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Node_DiskUsedPercent{node=~\"$PSM_Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rx Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "Node_InterfaceRxBytes{node=~\"$PSM_Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "Node_InterfaceTxBytes{node=~\"$PSM_Node\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}