{
 "title": "Switch Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Healthy DSS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Cluster_HealthyNICs / Cluster_AdmittedNICs",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total DSS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Cluster_AdmittedNICs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# VRFs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DSC_Number_of_vrfs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# VLANs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DSC_Number_of_networks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ELBA Enabled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DSC_ELBA_enabled", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IP Fragment Drops",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "targets": [
    { "expr": "IngressDrops_IPFragmentDrops", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Switch Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    { "expr": "DSC_node", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Sessions Over IPv4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(FlowStatsSummary_UDPSessionsOverIPv4) - sum(FlowStatsSummary_DeletedUDPSessionsOverIPv4)",
     "legendFormat": "UDP"
    },
    {
     "expr": "sum(FlowStatsSummary_TCPSessionsOverIPv4) - sum(FlowStatsSummary_DeletedTCPSessionsOverIPv4)",
     "legendFormat": "TCP"
    },
    {
     "expr": "sum(FlowStatsSummary_ICMPSessionsOverIPv4) - sum(FlowStatsSummary_DeletedICMPSessionsOverIPv4)",
     "legendFormat": "ICMP"
    },
    {
     "expr": "sum(FlowStatsSummary_OtherSessionsOverIPv4) - sum(FlowStatsSummary_DeletedOtherSessionsOverIPv4)",
     "legendFormat": "Other"
    },
    {
     "expr": "sum(FlowStatsSummary_L2Sessions) - sum(FlowStatsSummary_DeletedL2Sessions)",
     "legendFormat": "L2"
    }
   ]
  },
  {
   "title": "Switch Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DSC_health_status" }
   ]
  },
  {
   "title": "Active TCP Sessions IPv4",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "FlowStatsSummary_TCPSessionsOverIPv4 - FlowStatsSummary_DeletedTCPSessionsOverIPv4",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Active UDP Sessions IPv4",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "FlowStatsSummary_UDPSessionsOverIPv4 - FlowStatsSummary_DeletedUDPSessionsOverIPv4",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "ASIC Local Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "AsicTemperatureMetrics_LocalTemperature",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ASIC Die Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "AsicTemperatureMetrics_DieTemperature",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DSM Power In",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "targets": [
    { "expr": "PowerMetrics_Pin", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DSM Power Out1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
   "targets": [
    { "expr": "PowerMetrics_Pout1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DSM Power Out2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
   "targets": [
    { "expr": "PowerMetrics_Pout2", "legendFormat": "__auto" }
   ]
  }
 ]
}